### ISSUE TITLE
Feedback on week 13 project progress for CS2113T-W13-3

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113T-W13-3/main#203]
## Team progress for `v1.4`
* Milestone `v1.4` properly managed:
   * [x] A suitable deadline set [your deadline: 2019-11-10] (:heavy_check_mark: well done!)
   * [x] All issues in this milestone are closed(:heavy_check_mark: well done!)
   * [x] Milestone explicitly closed(:heavy_check_mark: well done!)
* [x] New JAR released on GitHub in the past 2 weeks (:heavy_check_mark: well done!)
## Individual progress of @jefferson111 for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-W13-3/main/pull/192 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/176 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/171 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/169 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/160 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/139 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/133 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/132 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/131 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/130 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/129 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/128 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/127 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/92 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/91 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @inno97 for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-W13-3/main/issues/171 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/148 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/144 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/139 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/133 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/132 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/131 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/130 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/129 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/128 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/92 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @sukrut1881 for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-W13-3/main/issues/178 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/168 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/167 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/166 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/165 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/160 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/145 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/139 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/133 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/132 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/131 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/130 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/129 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/128 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @hongchuan97 for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-W13-3/main/issues/174 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/164 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/148 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/139 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/133 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/132 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/131 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/130 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/129 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/128 https://github.com/AY1920S1-CS2113T-W13-3/main/issues/118 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)

Tutor: @okkhoy

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-11-13 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
